version: '3.1'

services:
  rabbitmq:
    build:
      context: ./docker/rabbitmq/
      dockerfile: rabbitmq-local.dockerfile
    ports:
      - "5671:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest1
  
  manager:
    build:
      context: ./docker/manager/
      dockerfile: manager-local.dockerfile
    volumes:
      - ./src/python:/usr/src/app
    environment:
      - PYTHONUNBUFFERED=1
    # restart: always
  worker:
    build:
      context: ./docker/workertest/
      dockerfile: worker-local.dockerfile
    volumes:
      - ./src/python:/usr/src/app
    environment:
      - PYTHONUNBUFFERED=1

networks: 
  default: 
    name: external-example 
    external: true