version: '3.1'

services:
  rabbitmq:
    build:
      context: ./docker/rabbitmq/
      dockerfile: rabbitmq-local.dockerfile
    ports:
      - "5671:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest1
    
    # restart: always
  worker:
    build:
      context: ./docker/worker/
      dockerfile: worker-local.dockerfile
    ports:
      - "5671:5672"
    volumes:
      - ./src/python:/usr/src/app

  manager:
    build:
      context: ./docker/manager/
      dockerfile: manager-local.dockerfile
    ports:
      - "5671:5672"
    volumes:
      - ./src/python:/usr/src/app