version: '3.1'

services:
  worker:
    build:
      context: ./docker/worker/
      #dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./g4bls_volume:/app/golang
    # restart: always

  manager:
    build:
      context: ./docker/manager/
      #dockerfile: Dockerfile
    ports:
      - "4311:4311"
    volumes:
      - ./src/python:/usr/src/app
    # restart: always
