site_name: g4bl_suite


repo_url: https://github.com/badumbatish/g4bl_suite
repo_name: 'GitHub'
theme:
  name: "material"

plugins:
  - search
  - mkdocstrings
nav:
  - Home: index.md
  - About: about.md
  - Automation: automation/README.md 
  - Code Reference:
    - g4blplot.py: g4bl_suite.g4blplot.reference.md
    - DataAnalyzer.py: g4bl_suite.DataAnalyzer.reference.md
    - GlobalVariables.py: g4bl_suite.GlobalVariables.reference.md



